name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Verify Build Directory
      run: ls -la dist/

    - name: Deploy to FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt-get install -y lftp
        echo "Testing FTP connection..."
        lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST -e "bye" || exit 1
        echo "FTP connection successful. Starting upload..."
        lftp -e "
          set ftp:ssl-allow no;
          set mirror:verbose yes;
          mirror -R dist/ /public_html/;
          bye;
        " -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
